Update run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -64,31 +64,25 @@ jobs:
       
       - name: Check Allure installation
         run: allure --version #Проверяем, установлен ли Allure
+        
       - name: Debug - Check Allure results folder
-        run: ls -l results #Убеждаемся, что папка results не пустая
+        run: ls -l results || echo "⚠️ Folder 'results' does not exist or is empty!" #Убеждаемся, что папка results не пустая
       
       - name: Generate Allure report  #Создаtv папку _site перед генерацией
         run: |
-          mkdir -p _site 
-          allure generate -c -o _site
+          mkdir -p _site
+          set -x
+          allure generate -c -o _site || echo "⚠️ Allure report generation failed!"
        
       - name: Debug - Check Allure report folder
-        run: ls -l _site  # Должны быть HTML-файлы
+        run: ls -l _site || echo "⚠️ No Allure report generated!"  # Должны быть HTML-файлы
 
-      - name: Generate report
-        run: allure generate -c -o _site
-      - name: Save raw Allure results
-        uses: actions/upload-artifact@v4
-        with:
-          name: allure-results
-          path: results
-          retention-days: 3
-      - name: Save report as artifact
+      - name: Upload Allure report
         uses: actions/upload-artifact@v4
         with:
           name: allure-report
           path: _site
-          retention-days: 3
+          retention-days: 1
 
 
   publish-report:
